<?php

function shiftcipher_menu() {
    $items['shiftcipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shiftcipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shiftcipher_success_page'] = array(
        'title' => 'Shift Cipher Results',
        'page callback' => 'shiftcipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shiftcipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('How many places would you like to shift each letter?'),
        '#attributes' => array('placeholder' => t('An integer greater than zero')),
        '#default_value' => isset($_SESSION['shiftcipher_shift_value']) ? $_SESSION['shiftcipher_shift_value'] : '',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['direction'] = array(
        '#title' => 'Direction',
        '#type' => 'textfield',
        '#description' => t('In which direction would you like to shift each letter (right or left)?'),
        '#default_value' => isset($_SESSION['shiftcipher_direction']) ? $_SESSION['shiftcipher_direction'] : '',
        '#attributes' => array('placeholder' => t('"Right" or "left" in all lowercase, without quotes')),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_direction'),
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter the phrase to encrypt.'),
        '#attributes' => array('placeholder' => t('Only letters, spaces, and punctuations accepted')),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_phrase'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'What Would Mr. (Lou) Cipher Say?',
    );
    return $form;
}

function shiftcipher_getdefault($variable_type) {
  return $_SESSION['shiftcipher_shift_value'];
}

function element_validate_direction($element) {
  if (!($element['#value'] == "left" || $element['#value'] == "right")) {
        form_error($element, t('The only valid Direction choices are "left" and "right".'));
  }
}

function element_validate_phrase($element) {
  if (preg_match("/[0-9\\\\~@#$%^&\*()_+={}|<>\/\`]/", $element['#value'])) {
        form_error($element, t('Only letters, spaces, and punctuation are allowed in the phrase.'));
  }
}

function shiftcipher_phrase($input_phrase, $shift, $direction) {
    $input_array = str_split($input_phrase);
    $output_array = array();
    foreach ($input_array as $input_letter) {
      if (preg_match("/[a-zA-Z]/", $input_letter)) {
          $output_array[] = shiftcipher_letter($input_letter, $shift, $direction);
      } else {
          $output_array[] = $input_letter;
      }
    }
    return join("", $output_array);
  }

function shiftcipher_letter($input_letter, $shift, $direction) {
    $alpha = " abcdefghijklmnopqrstuvwxyz";
    $shift = fmod(($direction == "right" ? $shift : -$shift), 26);
    $position_orig = stripos($alpha, strtolower($input_letter));
    $position_new = $position_orig + $shift;
    if ($position_new > 26) {
        $position_new -= 26;
    } elseif ($position_new < 1) {
        $position_new += 26;
    }
    return $alpha[(int)$position_new];
}

function shiftcipher_form_submit($form, &$form_state) {

    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    $encrypted_phrase = shiftcipher_phrase($phrase, $shift_value, $direction);
    $_SESSION['shiftcipher_shift_value'] = $shift_value;
    $_SESSION['shiftcipher_direction'] = $direction;
    $_SESSION['shiftcipher_phrase'] = $phrase;
    $_SESSION['shiftcipher_output'] = $encrypted_phrase;
    $form_state['redirect'] = 'shiftcipher_success_page';
}

function shiftcipher_success() {
    $shift_value = $_SESSION['shiftcipher_shift_value'];
    $direction = $_SESSION['shiftcipher_direction'];
    $phrase = $_SESSION['shiftcipher_phrase'];
    $answer = $_SESSION['shiftcipher_output'];
    $display_result = 'Mr. (Lou) Cipher has encrypted your phrase, <br>';
    $display_result .= '<strong>' . $phrase . '</strong><br> by shifting ' . $shift_value . ' to the ' . $direction . ' with the following result:<br>';
    $display_result .= '<strong>' . $answer . '</strong>';
    return $display_result;
}
